import type { TableViewDataTableColumnConfig } from "../ComponentLevelDataTableView";

/*
======================================
Set your module all field types here
======================================
*/
export type ModuleFieldsType = {
  patientId: string;
  doctorName: string;
  roomName: string;
  bedNumber: string;
  admissionDate: string;
  dischargeDate: string;
  packageName: string;
  insuranceName: string;
  policyNo: string;
  agentName: string;
  guardianName: string;
  guardianRelation: string;
  guardianContact: string;
  guardianAddress: string;
};

/*
  ============================
  initial Properties for permission and form: edit and create page
  ============================
*/

export const initialProperties: ModuleFieldsType = {
  patientId: "",
  doctorName: "",
  roomName: "",
  bedNumber: "",
  admissionDate: "",
  dischargeDate: "",
  packageName: "",
  insuranceName: "",
  policyNo: "",
  agentName: "",
  guardianName: "",
  guardianRelation: "",
  guardianContact: "",
  guardianAddress: "",
};

/*
======================================
Grid View Config
======================================
*/

// Add properties to this array to make them searchable

export const searchableKeys: (keyof ModuleFieldsType)[] = [
  "patientId",
  "doctorName",
  "roomName",
  "bedNumber",
  "admissionDate",
  "dischargeDate",
  "packageName",
  "insuranceName",
  "policyNo",
  "agentName",
  "guardianName",
  "guardianRelation",
  "guardianContact",
  "guardianAddress",
];

/*
======================================
Data Table View Config
======================================
*/

// Data table view data type
export type TableViewDataType = ModuleFieldsType & {
  id: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  draftedAt: string | null;
  actionMessage: string;
  isActive: boolean;
  isDraft: boolean;
  isDeleted: boolean;
  isUpdated: boolean;
};

// add value in array if you want to add fixed columns left side
export const fixedColumnsValues: (keyof ModuleFieldsType)[] = ["patientId"];

// column key and title for data table view
export const tableViewColumnSchema: TableViewDataTableColumnConfig[] = [
  { key: "patientId", title: "Patient ID" },
  { key: "doctorName", title: "Doctor Name" },
  { key: "roomName", title: "Room Name" },
  { key: "bedNumber", title: "Bed Number" },
  { key: "admissionDate", title: "Admission Date" },
  { key: "dischargeDate", title: "Discharge Date" },
  { key: "packageName", title: "Package Name" },
  { key: "insuranceName", title: "Insurance Name" },
  { key: "policyNo", title: "Policy No" },
  { key: "agentName", title: "Agent Name" },
  { key: "guardianName", title: "Guardian Name" },
  { key: "guardianRelation", title: "Guardian Relation" },
  { key: "guardianContact", title: "Guardian Contact" },
  { key: "guardianAddress", title: "Guardian Address" },
];

// dont change variable name "MOCK_TABLE_DATA"
export const MOCK_TABLE_DATA: TableViewDataType[] = [
  {
    id: "1",
    patientId: "P-1001",
    doctorName: "Dr. Rahman",
    roomName: "General Ward",
    bedNumber: "B-01",
    admissionDate: "2025-09-01",
    dischargeDate: "2025-09-05",
    packageName: "Standard Care",
    insuranceName: "GreenLife Insurance",
    policyNo: "INS-56789",
    agentName: "Mr. Karim",
    guardianName: "Abdul Karim",
    guardianRelation: "Father",
    guardianContact: "01710000001",
    guardianAddress: "Dhaka, Bangladesh",
    status: "Discharged",
    createdAt: "2025-09-01",
    updatedAt: "2025-09-05",
    draftedAt: null,
    actionMessage: "Patient discharged successfully",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "2",
    patientId: "P-1002",
    doctorName: "Dr. Sultana",
    roomName: "ICU",
    bedNumber: "ICU-05",
    admissionDate: "2025-09-02",
    dischargeDate: "",
    packageName: "Critical Care",
    insuranceName: "HealthFirst",
    policyNo: "INS-77890",
    agentName: "Mr. Rahim",
    guardianName: "Hasina Begum",
    guardianRelation: "Mother",
    guardianContact: "01710000002",
    guardianAddress: "Chattogram, Bangladesh",
    status: "Admitted",
    createdAt: "2025-09-02",
    updatedAt: "2025-09-03",
    draftedAt: null,
    actionMessage: "Patient under observation",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "3",
    patientId: "P-1003",
    doctorName: "Dr. Hasan",
    roomName: "Private Cabin",
    bedNumber: "C-12",
    admissionDate: "2025-09-01",
    dischargeDate: "2025-09-04",
    packageName: "Deluxe Package",
    insuranceName: "MediCare",
    policyNo: "INS-34567",
    agentName: "Ms. Laila",
    guardianName: "Shahidul Islam",
    guardianRelation: "Brother",
    guardianContact: "01710000003",
    guardianAddress: "Rajshahi, Bangladesh",
    status: "Discharged",
    createdAt: "2025-09-01",
    updatedAt: "2025-09-04",
    draftedAt: null,
    actionMessage: "Treatment completed",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "4",
    patientId: "P-1004",
    doctorName: "Dr. Nahar",
    roomName: "General Ward",
    bedNumber: "B-15",
    admissionDate: "2025-09-05",
    dischargeDate: "",
    packageName: "Basic Care",
    insuranceName: "CityHealth",
    policyNo: "INS-99887",
    agentName: "Mr. Amin",
    guardianName: "Nurul Amin",
    guardianRelation: "Father",
    guardianContact: "01710000004",
    guardianAddress: "Sylhet, Bangladesh",
    status: "Admitted",
    createdAt: "2025-09-05",
    updatedAt: "2025-09-05",
    draftedAt: null,
    actionMessage: "Patient admitted",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "5",
    patientId: "P-1005",
    doctorName: "Dr. Hossain",
    roomName: "ICU",
    bedNumber: "ICU-02",
    admissionDate: "2025-09-06",
    dischargeDate: "",
    packageName: "Emergency Care",
    insuranceName: "SecureLife",
    policyNo: "INS-22334",
    agentName: "Mr. Selim",
    guardianName: "Kamrul Hasan",
    guardianRelation: "Uncle",
    guardianContact: "01710000005",
    guardianAddress: "Barisal, Bangladesh",
    status: "Critical",
    createdAt: "2025-09-06",
    updatedAt: "2025-09-07",
    draftedAt: null,
    actionMessage: "Patient in critical condition",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "6",
    patientId: "P-1006",
    doctorName: "Dr. Alam",
    roomName: "Private Cabin",
    bedNumber: "C-05",
    admissionDate: "2025-09-03",
    dischargeDate: "2025-09-06",
    packageName: "Standard Care",
    insuranceName: "GreenLife Insurance",
    policyNo: "INS-88990",
    agentName: "Mr. Rashed",
    guardianName: "Rokeya Begum",
    guardianRelation: "Mother",
    guardianContact: "01710000006",
    guardianAddress: "Khulna, Bangladesh",
    status: "Discharged",
    createdAt: "2025-09-03",
    updatedAt: "2025-09-06",
    draftedAt: null,
    actionMessage: "Recovery successful",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "7",
    patientId: "P-1007",
    doctorName: "Dr. Kabir",
    roomName: "General Ward",
    bedNumber: "B-08",
    admissionDate: "2025-09-07",
    dischargeDate: "",
    packageName: "Basic Care",
    insuranceName: "MediCare",
    policyNo: "INS-44556",
    agentName: "Ms. Shila",
    guardianName: "Habibur Rahman",
    guardianRelation: "Father",
    guardianContact: "01710000007",
    guardianAddress: "Mymensingh, Bangladesh",
    status: "Admitted",
    createdAt: "2025-09-07",
    updatedAt: "2025-09-08",
    draftedAt: null,
    actionMessage: "Under treatment",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "8",
    patientId: "P-1008",
    doctorName: "Dr. Ferdous",
    roomName: "ICU",
    bedNumber: "ICU-10",
    admissionDate: "2025-09-08",
    dischargeDate: "",
    packageName: "Critical Care",
    insuranceName: "HealthFirst",
    policyNo: "INS-33445",
    agentName: "Mr. Mamun",
    guardianName: "Latifur Rahman",
    guardianRelation: "Brother",
    guardianContact: "01710000008",
    guardianAddress: "Rangpur, Bangladesh",
    status: "Critical",
    createdAt: "2025-09-08",
    updatedAt: "2025-09-09",
    draftedAt: null,
    actionMessage: "Monitoring closely",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "9",
    patientId: "P-1009",
    doctorName: "Dr. Jahan",
    roomName: "Private Cabin",
    bedNumber: "C-18",
    admissionDate: "2025-09-04",
    dischargeDate: "2025-09-08",
    packageName: "Deluxe Package",
    insuranceName: "CityHealth",
    policyNo: "INS-55667",
    agentName: "Mr. Babul",
    guardianName: "Sharmin Akter",
    guardianRelation: "Sister",
    guardianContact: "01710000009",
    guardianAddress: "Bogura, Bangladesh",
    status: "Discharged",
    createdAt: "2025-09-04",
    updatedAt: "2025-09-08",
    draftedAt: null,
    actionMessage: "Patient stable",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "10",
    patientId: "P-1010",
    doctorName: "Dr. Rumi",
    roomName: "General Ward",
    bedNumber: "B-22",
    admissionDate: "2025-09-09",
    dischargeDate: "",
    packageName: "Basic Care",
    insuranceName: "SecureLife",
    policyNo: "INS-77881",
    agentName: "Ms. Sonia",
    guardianName: "Mizanur Rahman",
    guardianRelation: "Father",
    guardianContact: "01710000010",
    guardianAddress: "Cumilla, Bangladesh",
    status: "Admitted",
    createdAt: "2025-09-09",
    updatedAt: "2025-09-10",
    draftedAt: null,
    actionMessage: "Initial tests ongoing",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "11",
    patientId: "P-1011",
    doctorName: "Dr. Parveen",
    roomName: "ICU",
    bedNumber: "ICU-03",
    admissionDate: "2025-09-10",
    dischargeDate: "",
    packageName: "Emergency Care",
    insuranceName: "MediCare",
    policyNo: "INS-66778",
    agentName: "Mr. Rafiq",
    guardianName: "Salma Khatun",
    guardianRelation: "Mother",
    guardianContact: "01710000011",
    guardianAddress: "Jashore, Bangladesh",
    status: "Critical",
    createdAt: "2025-09-10",
    updatedAt: "2025-09-11",
    draftedAt: null,
    actionMessage: "Patient under ventilation",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "12",
    patientId: "P-1012",
    doctorName: "Dr. Habib",
    roomName: "Private Cabin",
    bedNumber: "C-20",
    admissionDate: "2025-09-11",
    dischargeDate: "2025-09-13",
    packageName: "Standard Care",
    insuranceName: "GreenLife Insurance",
    policyNo: "INS-88991",
    agentName: "Mr. Nayeem",
    guardianName: "Faruk Ahmed",
    guardianRelation: "Uncle",
    guardianContact: "01710000012",
    guardianAddress: "Gazipur, Bangladesh",
    status: "Discharged",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    draftedAt: null,
    actionMessage: "Patient released after recovery",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
];

/* 
==========================
# Create Page Config
==========================
*/

// create page types
export type ModuleCreateEditPageTypes = ModuleFieldsType & {
  isDefault: boolean;
  isDraft: boolean;

  createdAt: Date | null;
  draftedAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};

// Utility to extract the keys of ModuleFieldsType whose values are strings
type StringKeys<T> = Extract<
  {
    [K in keyof T]-?: T[K] extends string ? K : never;
  }[keyof T],
  string
>;

// field config types
type FieldConfig = {
  name: StringKeys<ModuleFieldsType>;
  label: string;
  type?: React.HTMLInputTypeAttribute;
  component: "autocomplete" | "input" | "mutiselect";
  placeholder?: string;
  options?: string[];
  nextFocus?: string;
  tooltip?: string;
  required?: boolean;
};

export const initialDataWithValue: ModuleCreateEditPageTypes = {
  patientId: "P-1001",
  doctorName: "Dr. Rahman",
  roomName: "General Ward",
  bedNumber: "B-01",
  admissionDate: "2025-09-01",
  dischargeDate: "2025-09-05",
  packageName: "Standard Care",
  insuranceName: "GreenLife Insurance",
  policyNo: "INS-56789",
  agentName: "Mr. Karim",
  guardianName: "Abdul Karim",
  guardianRelation: "Father",
  guardianContact: "01710000001",
  guardianAddress: "Dhaka, Bangladesh",

  isDefault: false,
  isDraft: false,
  createdAt: new Date(),
  draftedAt: null,
  updatedAt: new Date(),
  deletedAt: null,
};

// add item for your nessasary fields
export const formFields: FieldConfig[] = [
  {
    name: "patientId",
    label: "Patient ID",
    nextFocus: "doctorName",
    component: "input",
    tooltip: "Enter patient id",
    required: true,
  },

  {
    name: "doctorName",
    type: "text",
    label: "Doctor Name",
    component: "autocomplete",
    options: [
      "Dr. Rahman",
      "Dr. Jahan",
      "Dr. Ferdous",
      "Dr. Rumi",
      "Dr. Parveen",
      "Dr. Habib",
    ],
    placeholder: " ",
    nextFocus: "roomName",
    tooltip: "Enter doctor name",
    required: true,
  },
  {
    name: "roomName",
    label: "Room Name",
    component: "autocomplete",
    nextFocus: "bedNumber",
    options: [
      "General Ward",
      "ICU",
      "Private Cabin",
      "Deluxe Cabin",
      "Super Deluxe Cabin",
      "Suite",
    ],
    placeholder: " ",
    tooltip: "Enter room name",
    required: true,
  },
  {
    name: "bedNumber",
    label: "Bed Number",
    component: "autocomplete",
    nextFocus: "admissionDate",
    options: ["B-01", "B-02", "B-03", "B-04", "B-05", "B-06"],
    placeholder: " ",
    tooltip: "Enter bed number",
    required: true,
  },
  {
    name: "admissionDate",
    label: "Admission Date",
    component: "input",
    type: "date",
    nextFocus: "dischargeDate",
    tooltip: "Enter admission date",
    required: true,
  },
  {
    name: "dischargeDate",
    label: "Discharge Date",
    component: "input",
    type: "date",
    nextFocus: "packageName",
    tooltip: "Enter discharge date",
    required: true,
  },
  {
    name: "packageName",
    label: "Package Name",
    component: "autocomplete",
    nextFocus: "insuranceName",
    options: ["Basic Care", "Standard Care", "Deluxe Care", "Premium Care"],
    placeholder: " ",
    tooltip: "Enter package name",
    required: true,
  },
  {
    name: "insuranceName",
    label: "Insurance Name",
    component: "autocomplete",
    nextFocus: "policyNo",
    options: ["GreenLife Insurance", "CityHealth", "MediCare", "SecureLife"],
    placeholder: " ",
    tooltip: "Enter insurance name",
    required: true,
  },
  {
    name: "policyNo",
    label: "Policy No",
    component: "input",
    nextFocus: "agentName",
    tooltip: "Enter policy number",
    required: true,
  },
  {
    name: "agentName",
    label: "Agent Name",
    component: "input",
    nextFocus: "guardianName",
    tooltip: "Enter agent name",
    required: true,
  },
  {
    name: "guardianName",
    label: "Guardian Name",
    component: "input",
    nextFocus: "guardianRelation",
    tooltip: "Enter guardian name",
    required: true,
  },
  {
    name: "guardianRelation",
    label: "Guardian Relation",
    component: "input",
    nextFocus: "guardianContact",
    tooltip: "Enter guardian relation",
    required: true,
  },
  {
    name: "guardianContact",
    label: "Guardian Contact",
    component: "input",
    nextFocus: "guardianAddress",
    tooltip: "Enter guardian contact",
    required: true,
  },
  {
    name: "guardianAddress",
    label: "Guardian Address",
    component: "input",
    nextFocus: "isDefault",
    tooltip: "Enter guardian address",
    required: true,
  },
];

/*
===============================
# PDF Config
===============================
*/

export const printConfigFieldLabels: ModuleFieldsType = {
  admissionDate: "Admission Date",
  agentName: "Agent Name",
  bedNumber: "Bed Number",
  doctorName: "Doctor Name",
  dischargeDate: "Discharge Date",
  guardianAddress: "Guardian Address",
  guardianContact: "Guardian Contact",
  guardianName: "Guardian Name",
  guardianRelation: "Guardian Relation",
  insuranceName: "Insurance Name",
  packageName: "Package Name",
  patientId: "Patient ID",
  roomName: "Room Name",
  policyNo: "Policy No",
};

// grid view

export type GridDataType = ModuleFieldsType & {
  id: string;
  isDefault: boolean;
  isActive: boolean;
  isDraft: boolean;
  createdAt: Date;
  draftedAt: Date | null;
  updatedAt: Date;
  deletedAt: Date | null;
  isDeleted: boolean;
};

export const gridviewData: GridDataType[] = [
  {
    id: "1",
    patientId: "P-1001",
    doctorName: "Dr. Ahsan Habib",
    roomName: "General Ward",
    bedNumber: "B-01",
    admissionDate: "2025-09-01",
    dischargeDate: "2025-09-05",
    packageName: "General Care",
    insuranceName: "Health Plus",
    policyNo: "HP-458721",
    agentName: "Rahim Uddin",
    guardianName: "Abdul Karim",
    guardianRelation: "Father",
    guardianContact: "01711111111",
    guardianAddress: "Dhaka, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-01"),
    draftedAt: null,
    updatedAt: new Date("2025-09-05"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "2",
    patientId: "P-1002",
    doctorName: "Dr. Nafisa Sultana",
    roomName: "ICU",
    bedNumber: "ICU-05",
    admissionDate: "2025-09-02",
    dischargeDate: "2025-09-07",
    packageName: "Critical Care",
    insuranceName: "MediCare",
    policyNo: "MC-745201",
    agentName: "Shakil Khan",
    guardianName: "Rashida Begum",
    guardianRelation: "Mother",
    guardianContact: "01722222222",
    guardianAddress: "Chittagong, Bangladesh",
    isDefault: true,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-02"),
    draftedAt: null,
    updatedAt: new Date("2025-09-07"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "3",
    patientId: "P-1003",
    doctorName: "Dr. Kamrul Hasan",
    roomName: "Private Cabin",
    bedNumber: "C-101",
    admissionDate: "2025-09-03",
    dischargeDate: "2025-09-10",
    packageName: "Premium Care",
    insuranceName: "SafeLife",
    policyNo: "SL-998123",
    agentName: "Tanvir Ahmed",
    guardianName: "Sajjad Hossain",
    guardianRelation: "Brother",
    guardianContact: "01733333333",
    guardianAddress: "Khulna, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-03"),
    draftedAt: null,
    updatedAt: new Date("2025-09-10"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "4",
    patientId: "P-1004",
    doctorName: "Dr. Farhana Rahman",
    roomName: "General Ward",
    bedNumber: "B-12",
    admissionDate: "2025-09-04",
    dischargeDate: "2025-09-09",
    packageName: "General Care",
    insuranceName: "Health Guard",
    policyNo: "HG-547896",
    agentName: "Jahidul Islam",
    guardianName: "Mehedi Hasan",
    guardianRelation: "Husband",
    guardianContact: "01744444444",
    guardianAddress: "Rajshahi, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-04"),
    draftedAt: null,
    updatedAt: new Date("2025-09-09"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "5",
    patientId: "P-1005",
    doctorName: "Dr. Anisur Rahman",
    roomName: "ICU",
    bedNumber: "ICU-03",
    admissionDate: "2025-09-05",
    dischargeDate: "2025-09-12",
    packageName: "Critical Care",
    insuranceName: "Life Shield",
    policyNo: "LS-336599",
    agentName: "Mamun Hossain",
    guardianName: "Jahanara Khatun",
    guardianRelation: "Mother",
    guardianContact: "01755555555",
    guardianAddress: "Sylhet, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-05"),
    draftedAt: null,
    updatedAt: new Date("2025-09-12"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "6",
    patientId: "P-1006",
    doctorName: "Dr. Maruf Chowdhury",
    roomName: "Private Cabin",
    bedNumber: "C-205",
    admissionDate: "2025-09-06",
    dischargeDate: "2025-09-14",
    packageName: "Premium Care",
    insuranceName: "MediCare",
    policyNo: "MC-789654",
    agentName: "Kamal Uddin",
    guardianName: "Nasir Uddin",
    guardianRelation: "Father",
    guardianContact: "01766666666",
    guardianAddress: "Barisal, Bangladesh",
    isDefault: false,
    isActive: false,
    isDraft: true,
    createdAt: new Date("2025-09-06"),
    draftedAt: new Date("2025-09-06"),
    updatedAt: new Date("2025-09-14"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "7",
    patientId: "P-1007",
    doctorName: "Dr. Shaila Akter",
    roomName: "General Ward",
    bedNumber: "B-15",
    admissionDate: "2025-09-07",
    dischargeDate: "2025-09-11",
    packageName: "General Care",
    insuranceName: "Health Plus",
    policyNo: "HP-741236",
    agentName: "Mahmudul Hasan",
    guardianName: "Abdul Malek",
    guardianRelation: "Father",
    guardianContact: "01777777777",
    guardianAddress: "Rangpur, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-07"),
    draftedAt: null,
    updatedAt: new Date("2025-09-11"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "8",
    patientId: "P-1008",
    doctorName: "Dr. Imran Hossain",
    roomName: "ICU",
    bedNumber: "ICU-08",
    admissionDate: "2025-09-08",
    dischargeDate: "2025-09-15",
    packageName: "Critical Care",
    insuranceName: "SafeLife",
    policyNo: "SL-635214",
    agentName: "Rafiq Khan",
    guardianName: "Selina Akter",
    guardianRelation: "Sister",
    guardianContact: "01788888888",
    guardianAddress: "Gazipur, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-08"),
    draftedAt: null,
    updatedAt: new Date("2025-09-15"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "9",
    patientId: "P-1009",
    doctorName: "Dr. Mahfuz Rahman",
    roomName: "Private Cabin",
    bedNumber: "C-302",
    admissionDate: "2025-09-09",
    dischargeDate: "2025-09-16",
    packageName: "Premium Care",
    insuranceName: "Health Guard",
    policyNo: "HG-741258",
    agentName: "Hasan Mahmud",
    guardianName: "Jalal Uddin",
    guardianRelation: "Brother",
    guardianContact: "01799999999",
    guardianAddress: "Mymensingh, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-09"),
    draftedAt: null,
    updatedAt: new Date("2025-09-16"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "10",
    patientId: "P-1010",
    doctorName: "Dr. Sohana Akter",
    roomName: "General Ward",
    bedNumber: "B-20",
    admissionDate: "2025-09-10",
    dischargeDate: "2025-09-14",
    packageName: "General Care",
    insuranceName: "Life Shield",
    policyNo: "LS-369852",
    agentName: "Bashir Ahmed",
    guardianName: "Nazmul Huda",
    guardianRelation: "Father",
    guardianContact: "01811111111",
    guardianAddress: "Comilla, Bangladesh",
    isDefault: false,
    isActive: false,
    isDraft: false,
    createdAt: new Date("2025-09-10"),
    draftedAt: null,
    updatedAt: new Date("2025-09-14"),
    deletedAt: new Date("2025-09-14"),
    isDeleted: true,
  },
  {
    id: "11",
    patientId: "P-1011",
    doctorName: "Dr. Arif Hossain",
    roomName: "ICU",
    bedNumber: "ICU-11",
    admissionDate: "2025-09-11",
    dischargeDate: "2025-09-18",
    packageName: "Critical Care",
    insuranceName: "MediCare",
    policyNo: "MC-258963",
    agentName: "Nayeem Hasan",
    guardianName: "Shirin Akter",
    guardianRelation: "Mother",
    guardianContact: "01822222222",
    guardianAddress: "Jessore, Bangladesh",
    isDefault: true,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-11"),
    draftedAt: null,
    updatedAt: new Date("2025-09-18"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "12",
    patientId: "P-1012",
    doctorName: "Dr. Rashedul Karim",
    roomName: "Private Cabin",
    bedNumber: "C-404",
    admissionDate: "2025-09-12",
    dischargeDate: "2025-09-20",
    packageName: "Premium Care",
    insuranceName: "Health Plus",
    policyNo: "HP-963741",
    agentName: "Shahriar Kabir",
    guardianName: "Sultan Ahmed",
    guardianRelation: "Uncle",
    guardianContact: "01833333333",
    guardianAddress: "Bogura, Bangladesh",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-12"),
    draftedAt: null,
    updatedAt: new Date("2025-09-20"),
    deletedAt: null,
    isDeleted: false,
  },
];
