export const mockBinHistoryData = [
  {
    id: "bin-001",
    name: "Bin A1",
    code: "BN-A1",
    description: "Main storage bin near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-002",
    name: "Bin A2",
    code: "BN-A2",
    description: "Main storage bin near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-003",
    name: "Bin A3",
    code: "BN-A3",
    description: "Main storage bin near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-004",
    name: "Bin A4",
    code: "BN-A4",
    description: "Main storage bin near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-005",
    name: "Bin A5",
    code: "BN-A5",
    description: "Main storage bin near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-006",
    name: "Bin A6",
    code: "BN-A6",
    description: "Main storage bin near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-007",
    name: "Bin A7",
    code: "BN-A7",
    description: "Main storage bin near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-008",
    name: "Bin A8",
    code: "BN-A8",
    description: "Main storage bin near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "bin-009",
    name: "Bin A9",
    code: "BN-A9",
    description: "Main storage bin near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "bin-010",
    name: "Bin A10",
    code: "BN-A10",
    description: "Main storage bin near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
