export const mockBrandsHistoryData = [
  {
    id: "1",
    name: "Nike",
    code: "NIKE",
    description: "Leading sportswear and athletic brand",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "2",

    name: "Adidas",
    code: "ADIDAS",
    description: "Premium athletic footwear and apparel brand",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "3",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "4",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "5",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "6",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "7",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "8",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "9",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "10",
    name: "New Brand",
    code: "newbrand",
    description: "New brand description",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
