export const mockColorHistoryData = [
  {
    id: "color-001",
    name: "Red",
    code: "RED",
    hexCode: "#FF0000",
    description: "Used for error or danger alerts",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-002",
    name: "Green",
    code: "GREEN",
    hexCode: "#00FF00",
    description: "Represents success or confirmation",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-003",
    name: "Blue",
    code: "BLUE",
    hexCode: "#0000FF",
    description: "Used for primary actions or links",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-004",
    name: "Yellow",
    code: "YELLOW",
    hexCode: "#FFFF00",
    description: "Warning or highlight indicators",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-005",
    name: "Black",
    code: "BLACK",
    hexCode: "#000000",
    description: "Standard for text or dark backgrounds",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-006",
    name: "White",
    code: "WHITE",
    hexCode: "#FFFFFF",
    description: "Used for backgrounds or light themes",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-007",
    name: "Orange",
    code: "ORANGE",
    hexCode: "#FFA500",
    description: "Accent color for promotions",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-008",
    name: "Purple",
    code: "PURPLE",
    hexCode: "#800080",
    description: "Used as a secondary theme color",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "color-009",
    name: "Red",
    code: "RED",
    hexCode: "#FF0000",
    description: "Used for error or danger alerts",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "color-010",
    name: "Red",
    code: "RED",
    hexCode: "#FF0000",
    description: "Used for error or danger alerts",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
