import type { Currency } from "@/types";

export const currencies: Currency[] = [
  {
    id: "1",
    code: "USD",
    currency: "US Dollar",
    exchange: 1,
    symbol: "$",

    isDefault: true,
    isActive: true,
    isDraft: false,
    isDeleted: false,

    createdAt: new Date("2023-01-01"),
    draftedAt: null,
    updatedAt: new Date("2024-01-01"),
    deletedAt: null,
  },
  {
    id: "2",
    code: "EUR",
    currency: "Euro",
    exchange: 1.09,
    symbol: "€",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-02-01"),
    draftedAt: null,
    updatedAt: new Date("2024-02-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "3",
    code: "GBP",
    currency: "British Pound",
    exchange: 1.27,
    symbol: "£",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-03-01"),
    draftedAt: null,
    updatedAt: new Date("2024-03-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "4",
    code: "JPY",
    currency: "Japanese Yen",
    exchange: 0.0069,
    symbol: "¥",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-04-01"),
    draftedAt: null,
    updatedAt: new Date("2024-04-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "5",
    code: "AUD",
    currency: "Australian Dollar",
    exchange: 0.67,
    symbol: "A$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-05-01"),
    draftedAt: null,
    updatedAt: new Date("2024-05-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "6",
    code: "CAD",
    currency: "Canadian Dollar",
    exchange: 0.75,
    symbol: "C$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-06-01"),
    draftedAt: null,
    updatedAt: new Date("2024-06-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "7",
    code: "CHF",
    currency: "Swiss Franc",
    exchange: 1.13,
    symbol: "CHF",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-07-01"),
    draftedAt: null,
    updatedAt: new Date("2024-07-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "8",
    code: "CNY",
    currency: "Chinese Yuan",
    exchange: 0.14,
    symbol: "¥",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-08-01"),
    draftedAt: null,
    updatedAt: new Date("2024-08-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "9",
    code: "INR",
    currency: "Indian Rupee",
    exchange: 0.012,
    symbol: "₹",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-09-01"),
    draftedAt: null,
    updatedAt: new Date("2024-09-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "10",
    code: "BDT",
    currency: "Bangladeshi Taka",
    exchange: 0.0091,
    symbol: "৳",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-10-01"),
    draftedAt: null,
    updatedAt: new Date("2024-10-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "11",
    code: "SGD",
    currency: "Singapore Dollar",
    exchange: 0.74,
    symbol: "S$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-11-01"),
    draftedAt: null,
    updatedAt: new Date("2024-11-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "12",
    code: "HKD",
    currency: "Hong Kong Dollar",
    exchange: 0.13,
    symbol: "HK$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-12-01"),
    draftedAt: null,
    updatedAt: new Date("2024-12-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "13",
    code: "NZD",
    currency: "New Zealand Dollar",
    exchange: 0.61,
    symbol: "NZ$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-01-01"),
    draftedAt: null,
    updatedAt: new Date("2024-01-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "14",
    code: "SEK",
    currency: "Swedish Krona",
    exchange: 0.093,
    symbol: "kr",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-02-01"),
    draftedAt: null,
    updatedAt: new Date("2024-02-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "15",
    code: "NOK",
    currency: "Norwegian Krone",
    exchange: 0.095,
    symbol: "kr",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-03-01"),
    draftedAt: null,
    updatedAt: new Date("2024-03-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "16",
    code: "DKK",
    currency: "Danish Krone",
    exchange: 0.15,
    symbol: "kr",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-04-01"),
    draftedAt: null,
    updatedAt: new Date("2024-04-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "17",
    code: "ZAR",
    currency: "South African Rand",
    exchange: 0.054,
    symbol: "R",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-05-01"),
    draftedAt: null,
    updatedAt: new Date("2024-05-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "18",
    code: "BRL",
    currency: "Brazilian Real",
    exchange: 0.19,
    symbol: "R$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-06-01"),
    draftedAt: null,
    updatedAt: new Date("2024-06-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "19",
    code: "MXN",
    currency: "Mexican Peso",
    exchange: 0.058,
    symbol: "$",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-07-01"),
    draftedAt: null,
    updatedAt: new Date("2024-07-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "20",
    code: "RUB",
    currency: "Russian Ruble",
    exchange: 0.011,
    symbol: "₽",
    isDefault: false,
    isActive: false,
    isDraft: true,
    createdAt: new Date("2023-08-01"),
    draftedAt: new Date("2023-08-15"),
    updatedAt: new Date("2024-08-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "21",
    code: "TRY",
    currency: "Turkish Lira",
    exchange: 0.031,
    symbol: "₺",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-09-01"),
    draftedAt: null,
    updatedAt: new Date("2024-09-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "22",
    code: "THB",
    currency: "Thai Baht",
    exchange: 0.027,
    symbol: "฿",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-10-01"),
    draftedAt: null,
    updatedAt: new Date("2024-10-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "23",
    code: "KRW",
    currency: "South Korean Won",
    exchange: 0.00077,
    symbol: "₩",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-11-01"),
    draftedAt: null,
    updatedAt: new Date("2024-11-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "24",
    code: "IDR",
    currency: "Indonesian Rupiah",
    exchange: 6.5e-5,
    symbol: "Rp",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-12-01"),
    draftedAt: null,
    updatedAt: new Date("2024-12-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "25",
    code: "MYR",
    currency: "Malaysian Ringgit",
    exchange: 0.21,
    symbol: "RM",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-01-01"),
    draftedAt: null,
    updatedAt: new Date("2024-01-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "26",
    code: "PKR",
    currency: "Pakistani Rupee",
    exchange: 0.0036,
    symbol: "₨",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-02-01"),
    draftedAt: null,
    updatedAt: new Date("2024-02-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "27",
    code: "EGP",
    currency: "Egyptian Pound",
    exchange: 0.021,
    symbol: "£",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-03-01"),
    draftedAt: null,
    updatedAt: new Date("2024-03-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "28",
    code: "VND",
    currency: "Vietnamese Dong",
    exchange: 4.1e-5,
    symbol: "₫",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-04-01"),
    draftedAt: null,
    updatedAt: new Date("2024-04-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "29",
    code: "ILS",
    currency: "Israeli New Shekel",
    exchange: 0.27,
    symbol: "₪",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-05-01"),
    draftedAt: null,
    updatedAt: new Date("2024-05-01"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "30",
    code: "AED",
    currency: "UAE Dirham",
    exchange: 0.27,
    symbol: "د.إ",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-06-01"),
    draftedAt: null,
    updatedAt: new Date("2024-06-01"),
    deletedAt: null,
    isDeleted: false,
  },
];

export const currencyNames = [
  "Dollar",
  "Euro",
  "Yen",
  "Pound",
  "Rupee",
  "Ruble",
  "Won",
  "Lira",
  "Dong",
  "Shekel",
  "Peso",
  "Naira",
  "Hryvnia",
  "Guarani",
  "Colon",
  "Cedi",
  "Tenge",
  "Kip",
  "Tugrik",
  "Naira",
  "Rupee",
  "Ecu",
  "Cruzeiro",
  "Franc",
  "Lira",
  "Mark",
  "Peseta",
  "Drachma",
  "Pfennig",
  "Peso",
  "Guarani",
  "Austral",
  "Hryvnia",
  "Cedi",
  "Tenge",
  "Lira",
  "Manat",
  "Ruble",
  "Lari",
  "Bitcoin",
];

export const currencySymbols = [
  "$",
  "€",
  "¥",
  "£",
  "₹",
  "₽",
  "₩",
  "₺",
  "₫",
  "₪",
  "₱",
  "₦",
  "₴",
  "₲",
  "₡",
  "₵",
  "₸",
  "₭",
  "₮",
  "₦",
  "₨",
  "₠",
  "₢",
  "₣",
  "₤",
  "₥",
  "₧",
  "₯",
  "₰",
  "₱",
  "₲",
  "₳",
  "₴",
  "₵",
  "₸",
  "₺",
  "₼",
  "₽",
  "₾",
  "₿",
];
