export const mockDeliverymenHistoryData = [
  {
    id: "dm-001",
    code: "DM001",
    name: "Rahim Uddin",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-002",
    code: "DM002",
    name: "Adidas",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-003",
    code: "DM003",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-004",
    code: "DM004",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-005",
    code: "DM005",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-006",
    code: "DM006",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-007",
    code: "DM007",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-008",
    code: "DM008",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "dm-009",
    code: "DM009",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "dm-010",
    code: "DM010",
    name: "New Brand",
    phoneNumber: "01711112222",
    email: "rahim@example.com",
    address: "Mirpur, Dhaka",
    nationalId: "1234567890",

    assignedArea: "Mirpur",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
