export const mockDivisionsHistoryData = [
  {
    id: "divisions-001",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-002",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-003",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-004",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-005",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-006",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-007",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-008",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "divisions-009",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "divisions-010",
    name: "Dhaka Division",
    code: "DHK",
    region: "Central",
    description: "Covers the capital and nearby areas",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
