export const mockGroupsHistoryData = [
  {
    id: "groups-001",
    name: "Admin Group",
    code: "ADMIN",
    description: "System administrators with full access",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-002",
    name: "Main Distribution",
    code: "MAIN-DT",
    description: "Central storage for all distribution",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-003",
    name: "Admin Group",
    code: "ADMIN",
    description: "System administrators with full access",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-004",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-005",
    name: "Admin Group",
    code: "ADMIN",
    description: "System administrators with full access",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-006",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-007",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-008",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "groups-009",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "groups-010",
    name: "Main Transfer",
    code: "MAIN-TR",
    description: "Central storage for all transfer",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
