export const mockOrderTypeHistoryData = [
  {
    id: "1",
    typeName: "Dine-in",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "2",

    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "3",
    typeName: "Dine-in",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "4",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "5",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "6",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "7",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "8",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "9",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "10",
    typeName: "Delivery",
    description: "Self-service dine-in option",
    customerId: "cus-012",
    requiresDeliveryman: false,

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
