export const mockRackHistoryData = [
  {
    id: "rack-001",
    name: "Rack A1",
    code: "RK-A1",
    description: "Main storage rack near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-002",
    name: "Rack A2",
    code: "RK-A2",
    description: "Main storage rack near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-003",
    name: "Rack A3",
    code: "RK-A3",
    description: "Main storage rack near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-004",
    name: "Rack A4",
    code: "RK-A4",
    description: "Main storage rack near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-005",
    name: "Rack A5",
    code: "RK-A5",
    description: "Main storage rack near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-006",
    name: "Rack A6",
    code: "RK-A6",
    description: "Main storage rack near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-007",
    name: "Rack A7",
    code: "RK-A7",
    description: "Main storage rack near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-008",
    name: "Rack A8",
    code: "RK-A8",
    description: "Main storage rack near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "rack-009",
    name: "Rack A9",
    code: "RK-A9",
    description: "Main storage rack near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "rack-010",
    name: "Rack A10",
    code: "RK-A10",
    description: "Main storage rack near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
