export const mockReservationHistoryData = [
  {
    id: "1",
    reservationNo: "RSV1001",
    reservationDate: "2025-07-09",
    customerName: "Rahim Uddin",
    table: "T01",
    persons: 2,
    startTime: "18:30",
    endTime: "20:00",
    mobile: "01710000001",
    phone: "029999001",
    email: "rahim@example.com",
    description: "Near main entrance, window seat.",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "2",

    reservationNo: "RSV1002",
    reservationDate: "2025-07-08",
    customerName: "Karim Mia",
    table: "T02",
    persons: 4,
    startTime: "19:00",
    endTime: "21:00",
    mobile: "01710000002",
    phone: "029999002",
    email: "karim@example.com",
    description: "Corner table, 4 seats",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "3",
    reservationNo: "RSV1003",
    reservationDate: "2025-07-10",
    customerName: "Salma Akter",
    table: "T03",
    persons: 6,
    startTime: "17:30",
    endTime: "19:30",
    mobile: "01710000003",
    phone: "029999003",
    email: "salma@example.com",
    description: "Family table with 6 seats",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "4",
    reservationNo: "RSV1004",
    reservationDate: "2025-07-11",
    customerName: "Nayeem Hasan",
    table: "T04",
    persons: 3,
    startTime: "20:00",
    endTime: "22:00",
    mobile: "01710000004",
    phone: "029999004",
    email: "nayeem@example.com",
    description: "Near stage, VIP zone",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "5",
    reservationNo: "RSV1005",
    reservationDate: "2025-07-06",
    customerName: "Jhumur Begum",
    table: "T05",
    persons: 1,
    startTime: "18:00",
    endTime: "19:00",
    mobile: "01710000005",
    phone: "029999005",
    email: "jhumur@example.com",
    description: "Outdoor seating",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "6",
    reservationNo: "RSV1006",
    reservationDate: "2025-07-07",
    customerName: "Shamim Reza",
    table: "T06",
    persons: 4,
    startTime: "19:15",
    endTime: "21:15",
    mobile: "01710000006",
    phone: "029999006",
    email: "shamim@example.com",
    description: "Near restrooms, 4 seats",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "7",
    reservationNo: "RSV1007",
    reservationDate: "2025-07-09",
    customerName: "Anika Sultana",
    table: "T07",
    persons: 2,
    startTime: "17:00",
    endTime: "18:30",
    mobile: "01710000007",
    phone: "029999007",
    email: "anika@example.com",
    description: "Private booth",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "8",
    reservationNo: "RSV1008",
    reservationDate: "2025-07-12",
    customerName: "Imran Hossain",
    table: "T08",
    persons: 4,
    startTime: "20:00",
    endTime: "22:00",
    mobile: "01710000008",
    phone: "029999008",
    email: "imran@example.com",
    description: "Middle of main hall",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "9",
    reservationNo: "RSV1009",
    reservationDate: "2025-07-10",
    customerName: "Sarah Jahan",
    table: "T09",
    persons: 2,
    startTime: "19:00",
    endTime: "20:30",
    mobile: "01710000009",
    phone: "029999009",
    email: "sarah@example.com",
    description: "Kids area table",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "10",
    reservationNo: "RSV1010",
    reservationDate: "2025-07-08",
    customerName: "Ahmed Hossain",
    table: "T10",
    persons: 3,
    startTime: "18:45",
    endTime: "20:00",
    mobile: "01710000010",
    phone: "029999010",
    email: "ahmed@example.com",
    description: "Close to kitchen",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
