export const mockSectionsHistoryData = [
  {
    id: "sections-001",
    name: "Dining Area A",
    code: "DIN-A",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-002",
    name: "Dining Area B",
    code: "DIN-B",
    type: "Dining",
    description: "Main seating area for customers",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-003",
    name: "Dining Area C",
    code: "DIN-C",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-004",
    name: "Dining Area D",
    code: "DIN-D",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-005",
    name: "Dining Area E",
    code: "DIN-E",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-006",
    name: "Dining Area F",
    code: "DIN-F",
    type: "Dining",
    description: "Main seating area for customers",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-007",
    name: "Dining Area G",
    code: "DIN-G",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-008",
    name: "Dining Area H",
    code: "DIN-H",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "sections-009",
    name: "Dining Area I",
    code: "DIN-I",
    type: "Dining",
    description: "Main seating area for customers",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "sections-010",
    name: "Dining Area J",
    code: "DIN-J",
    type: "Dining",
    description: "Main seating area for customers",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
