export const mockShelfHistoryData = [
  {
    id: "shelf-001",
    name: "Shelf A1",
    code: "SH-A1",
    description: "Main storage shelf near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-002",
    name: "Shelf A2",
    code: "SH-A2",
    description: "Main storage shelf near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-003",
    name: "Shelf A3",
    code: "SH-A3",
    description: "Main storage shelf near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-004",
    name: "Shelf A4",
    code: "SH-A4",
    description: "Main storage shelf near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-005",
    name: "Shelf A5",
    code: "SH-A5",
    description: "Main storage shelf near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-006",
    name: "Shelf A6",
    code: "SH-A6",
    description: "Main storage shelf near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-007",
    name: "Shelf A7",
    code: "SH-A7",
    description: "Main storage shelf near entrance",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-008",
    name: "Shelf A8",
    code: "SH-A8",
    description: "Main storage shelf near entrance",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "shelf-009",
    name: "Shelf A9",
    code: "SH-A9",
    description: "Main storage shelf near entrance",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "shelf-010",
    name: "Shelf A10",
    code: "SH-A10",
    description: "Main storage shelf near entrance",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
