export const mockSizeHistoryData = [
  {
    id: "size-001",
    name: "Small",
    code: "S",
    value: "28x20 cm",
    description: "Standard small size",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-002",
    name: "Medium",
    code: "M",
    value: "28x20 cm",
    description: "Standard medium size",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-003",
    name: "Large",
    code: "L",
    value: "28x20 cm",
    description: "Standard large size",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-004",
    name: "Extra Large",
    code: "XL",
    value: "28x20 cm",
    description: "Standard extra large size",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-005",
    name: "Extra Extra Large",
    code: "XXL",
    value: "28x20 cm",
    description: "Standard extra extra large size",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-006",
    name: "3XL",
    code: "3XL",
    value: "28x20 cm",
    description: "Used for backgrounds or light themes",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-007",
    name: "4XL",
    code: "4XL",
    value: "28x20 cm",
    description: "Used for backgrounds or light themes",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-008",
    name: "5XL",
    code: "5XL",
    value: "28x20 cm",
    description: "Used as a secondary theme color",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "size-009",
    name: "6XL",
    code: "6XL",
    value: "28x20 cm",
    description: "Used for error or danger alerts",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "size-010",
    name: "7XL",
    code: "7XL",
    value: "28x20 cm",
    description: "Used for error or danger alerts",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
