export const mockTableAssignHistoryData = [
  {
    id: "1",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Rahim Uddin",
    tableNo: "T01",
    description: "Near main entrance, 2 seats",
    photo: "/customer-dummy-image.jpg",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "2",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Karim Mia",
    tableNo: "T02",
    description: "Corner table, 4 seats",
    photo: "/customer-dummy-image.jpg",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "3",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Salma Akter",
    tableNo: "T03",
    description: "Family table with 6 seats",
    photo: "/customer-dummy-image.jpg",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "4",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Nayeem Hasan",
    tableNo: "T04",
    description: "Near stage, VIP zone",
    photo: "/customer-dummy-image.jpg",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "5",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Jhumur Begum",
    tableNo: "T05",
    description: "Outdoor seating",
    photo: "/customer-dummy-image.jpg",
    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "6",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Shamim Reza",
    tableNo: "T06",
    description: "Near restrooms, 4 seats",
    photo: "/customer-dummy-image.jpg",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "7",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Anika Sultana",
    tableNo: "T07",
    description: "Private booth",
    photo: "/customer-dummy-image.jpg",
    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "8",
    date: "11-01-2025 3:15:10 PM",
    waiterName: "Imran Hossain",
    tableNo: "T08",
    description: "Middle of main hall",
    photo: "/customer-dummy-image.jpg",
    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "9",
    date: "10-01-2025 2:45:30 PM",
    waiterName: "Sarah Jahan",
    tableNo: "T09",
    description: "Kids area table",
    photo: "/customer-dummy-image.jpg",
    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "10",
    date: "10-01-2025 1:20:15 PM",
    waiterName: "Ahmed Hossain",
    tableNo: "T10",
    description: "Close to kitchen",
    photo: "/customer-dummy-image.jpg",
    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
