import type { UserMasterData } from "@/types/userMaster.types";

export const mockUserMasterData: UserMasterData[] = [
  {
    id: "1",
    name: "John Doe",
    mobileNumber: "+1234567890",
    countryCode: "+1",
    email: "john.doe@example.com",
    password: "password123",
    confirmPassword: "password123",
    otp: "123456",
    facebook: "https://facebook.com/johndoe",
    linkedin: "https://linkedin.com/in/johndoe",
    instagram: "https://instagram.com/johndoe",
    code: "US001",
    state: "California",
    country: "United States",
    userType: "admin",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-01-10"),
    draftedAt: null,
    updatedAt: new Date("2023-06-15"),
    deletedAt: null,
    isDeleted: false,
    status: "active",
  },
  {
    id: "2",
    name: "Jane Smith",
    mobileNumber: "+1987654321",
    countryCode: "+1",
    email: "jane.smith@example.com",
    password: "password456",
    confirmPassword: "password456",
    otp: "654321",
    facebook: "https://facebook.com/janesmith",
    linkedin: "https://linkedin.com/in/janesmith",
    instagram: "https://instagram.com/janesmith",
    code: "US002",
    state: "New York",
    country: "United States",
    userType: "super_admin",
    isDefault: true,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-02-05"),
    draftedAt: null,
    updatedAt: new Date("2023-07-10"),
    deletedAt: null,
    isDeleted: false,
    status: "active",
  },
  {
    id: "3",
    name: "Mike Johnson",
    mobileNumber: "+44123456789",
    countryCode: "+44",
    email: "mike.johnson@example.com",
    password: "password789",
    confirmPassword: "password789",
    otp: "987654",
    facebook: "https://facebook.com/mikejohnson",
    linkedin: "https://linkedin.com/in/mikejohnson",
    instagram: "https://instagram.com/mikejohnson",
    code: "UK001",
    state: "London",
    country: "United Kingdom",
    userType: "super_user",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-03-01"),
    draftedAt: null,
    updatedAt: new Date("2023-08-05"),
    deletedAt: null,
    isDeleted: false,
    status: "active",
  },
  {
    id: "4",
    name: "Sarah Williams",
    mobileNumber: "+49123456789",
    countryCode: "+49",
    email: "sarah.williams@example.com",
    password: "password101",
    confirmPassword: "password101",
    otp: "101112",
    facebook: "",
    linkedin: "https://linkedin.com/in/sarahwilliams",
    instagram: "",
    code: "DE001",
    state: "Bavaria",
    country: "Germany",
    userType: "user",
    isDefault: false,
    isActive: false,
    isDraft: true,
    createdAt: new Date("2023-04-02"),
    draftedAt: new Date("2023-03-28"),
    updatedAt: new Date("2023-09-01"),
    deletedAt: null,
    isDeleted: false,
    status: "draft",
  },
  {
    id: "5",
    name: "David Brown",
    mobileNumber: "+91123456789",
    countryCode: "+91",
    email: "david.brown@example.com",
    password: "password111",
    confirmPassword: "password111",
    otp: "111213",
    facebook: "https://facebook.com/davidbrown",
    linkedin: "",
    instagram: "https://instagram.com/davidbrown",
    code: "IN001",
    state: "Maharashtra",
    country: "India",
    userType: "user",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-05-18"),
    draftedAt: null,
    updatedAt: new Date("2023-10-02"),
    deletedAt: null,
    isDeleted: false,
    status: "active",
  },
  {
    id: "6",
    name: "Emma Wilson",
    mobileNumber: "+61234567890",
    countryCode: "+61",
    email: "emma.wilson@example.com",
    password: "password121",
    confirmPassword: "password121",
    otp: "121314",
    facebook: "https://facebook.com/emmawilson",
    linkedin: "https://linkedin.com/in/emmawilson",
    instagram: "https://instagram.com/emmawilson",
    code: "AU001",
    state: "New South Wales",
    country: "Australia",
    userType: "admin",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2023-06-10"),
    draftedAt: null,
    updatedAt: new Date("2023-11-15"),
    deletedAt: null,
    isDeleted: false,
    status: "active",
  },
  {
    id: "7",
    name: "Carlos Rodriguez",
    mobileNumber: "+34123456789",
    countryCode: "+34",
    email: "carlos.rodriguez@example.com",
    password: "password131",
    confirmPassword: "password131",
    otp: "131415",
    facebook: "",
    linkedin: "https://linkedin.com/in/carlosrodriguez",
    instagram: "https://instagram.com/carlosrodriguez",
    code: "ES001",
    state: "Madrid",
    country: "Spain",
    userType: "user",
    isDefault: false,
    isActive: false,
    isDraft: false,
    createdAt: new Date("2023-07-05"),
    draftedAt: null,
    updatedAt: new Date("2023-12-01"),
    deletedAt: null,
    isDeleted: false,
    status: "inactive",
  },
  {
    id: "8",
    name: "Anna Mueller",
    mobileNumber: "+43123456789",
    countryCode: "+43",
    email: "anna.mueller@example.com",
    password: "password141",
    confirmPassword: "password141",
    otp: "141516",
    facebook: "https://facebook.com/annamueller",
    linkedin: "",
    instagram: "",
    code: "AT001",
    state: "Vienna",
    country: "Austria",
    userType: "super_user",
    isDefault: false,
    isActive: true,
    isDraft: true,
    createdAt: new Date("2023-08-12"),
    draftedAt: new Date("2023-08-10"),
    updatedAt: new Date("2023-12-20"),
    deletedAt: null,
    isDeleted: false,
    status: "draft",
  },

];

export const initialUserMasterData: UserMasterData = {
  name: "",
  mobileNumber: "",
  countryCode: "+1",
  email: "",
  password: "",
  confirmPassword: "",
  otp: "",
  facebook: "",
  linkedin: "",
  instagram: "",
  code: "",
  state: "",
  country: "",
  userType: "",
  isDefault: false,
  isActive: true,
  isDraft: false,
  createdAt: null,
  draftedAt: null,
  updatedAt: null,
  deletedAt: null,
  isDeleted: false,
  status: "active",
};
