export const mockWarehouseHistoryData = [
  {
    id: "warehouse-001",
    code: "MAIN-ST",
    name: "Main Storage",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all supplies",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-002",
    code: "MAIN-DT",
    name: "Main Distribution",
    location: "Banani, Bangladesh",
    manager: "Jonh Mia",
    description: "Central storage for all distribution",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-003",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-004",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-005",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Active" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-006",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-007",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Delete" as const,
    export: "Single" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-008",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Draft" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: false,
    xls: false,
    doc: false,
    print: false,
  },
  {
    id: "warehouse-009",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "Active" as const,
    export: "Single" as const,
    pdf: false,
    csv: true,
    xls: false,
    doc: false,
    print: true,
  },
  {
    id: "warehouse-010",
    code: "MAIN-TR",
    name: "Main Transfer",
    location: "Dhaka, Bangladesh",
    manager: "Jamil Ahmed",
    description: "Central storage for all transfer",

    status: "InActive" as const,
    export: "Bulk" as const,
    pdf: true,
    csv: true,
    xls: false,
    doc: false,
    print: false,
  },
];
