import type { TableViewDataTableColumnConfig } from "../ComponentLevelDataTableView";

/*
======================================
Set your module all field types here
======================================
*/
export type ModuleFieldsType = {
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  salesAgent: string;
  subTotal: string;
  discount: string;
  taxable: string;
  tax: string;
  total: string;
};

/*
  ============================
  initial Properties for permission and form: edit and create page
  ============================
*/

export const initialProperties: ModuleFieldsType = {
  invoiceNumber: "",
  customerId: "",
  customerName: "",
  salesAgent: "",
  subTotal: "",
  discount: "",
  taxable: "",
  tax: "",
  total: "",
};

/*
======================================
Grid View Config
======================================
*/

// Add properties to this array to make them searchable

export const searchableKeys: (keyof ModuleFieldsType)[] = [
  "invoiceNumber",
  "customerId",
  "customerName",
  "salesAgent",
  "subTotal",
  "discount",
  "taxable",
  "tax",
  "total",
];

/*
======================================
Data Table View Config
======================================
*/

// Data table view data type
export type TableViewDataType = ModuleFieldsType & {
  id: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  draftedAt: string | null;
  actionMessage: string;
  isActive: boolean;
  isDraft: boolean;
  isDeleted: boolean;
  isUpdated: boolean;
};

// add value in array if you want to add fixed columns left side
export const fixedColumnsValues: (keyof ModuleFieldsType)[] = ["invoiceNumber"];

// column key and title for data table view
export const tableViewColumnSchema: TableViewDataTableColumnConfig[] = [
  { key: "invoiceNumber", title: "Invoice Number" },
  { key: "customerId", title: "Customer ID" },
  { key: "customerName", title: "Customer Name" },
  { key: "salesAgent", title: "Sales Agent" },
  { key: "subTotal", title: "Sub Total" },
  { key: "discount", title: "Discount" },
  { key: "taxable", title: "Taxable" },
  { key: "tax", title: "Tax" },
  { key: "total", title: "Total" },
];

// dont change variable name "MOCK_TABLE_DATA"
export const MOCK_TABLE_DATA: TableViewDataType[] = [
  {
    id: "1",
    invoiceNumber: "INV-1001",
    customerId: "CUST-001",
    customerName: "John Doe",
    salesAgent: "Alice",
    subTotal: "500",
    discount: "50",
    taxable: "450",
    tax: "45",
    total: "495",
    status: "Completed",
    createdAt: "2025-09-01",
    updatedAt: "2025-09-02",
    draftedAt: null,
    actionMessage: "Invoice finalized",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "2",
    invoiceNumber: "INV-1002",
    customerId: "CUST-002",
    customerName: "Jane Smith",
    salesAgent: "Bob",
    subTotal: "800",
    discount: "100",
    taxable: "700",
    tax: "70",
    total: "770",
    status: "Pending",
    createdAt: "2025-09-03",
    updatedAt: "2025-09-03",
    draftedAt: null,
    actionMessage: "Awaiting payment",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "3",
    invoiceNumber: "INV-1003",
    customerId: "CUST-003",
    customerName: "Michael Johnson",
    salesAgent: "Charlie",
    subTotal: "1200",
    discount: "150",
    taxable: "1050",
    tax: "105",
    total: "1155",
    status: "Completed",
    createdAt: "2025-08-25",
    updatedAt: "2025-08-30",
    draftedAt: null,
    actionMessage: "Invoice paid",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "4",
    invoiceNumber: "INV-1004",
    customerId: "CUST-004",
    customerName: "Emily Davis",
    salesAgent: "Alice",
    subTotal: "300",
    discount: "20",
    taxable: "280",
    tax: "28",
    total: "308",
    status: "Draft",
    createdAt: "2025-09-05",
    updatedAt: "2025-09-05",
    draftedAt: "2025-09-05",
    actionMessage: "Draft created",
    isActive: false,
    isDraft: true,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "5",
    invoiceNumber: "INV-1005",
    customerId: "CUST-005",
    customerName: "David Wilson",
    salesAgent: "Bob",
    subTotal: "950",
    discount: "100",
    taxable: "850",
    tax: "85",
    total: "935",
    status: "Completed",
    createdAt: "2025-08-28",
    updatedAt: "2025-08-29",
    draftedAt: null,
    actionMessage: "Payment confirmed",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "6",
    invoiceNumber: "INV-1006",
    customerId: "CUST-006",
    customerName: "Sophia Martinez",
    salesAgent: "Charlie",
    subTotal: "400",
    discount: "30",
    taxable: "370",
    tax: "37",
    total: "407",
    status: "Cancelled",
    createdAt: "2025-08-20",
    updatedAt: "2025-08-21",
    draftedAt: null,
    actionMessage: "Invoice cancelled",
    isActive: false,
    isDraft: false,
    isDeleted: true,
    isUpdated: false,
  },
  {
    id: "7",
    invoiceNumber: "INV-1007",
    customerId: "CUST-007",
    customerName: "Olivia Brown",
    salesAgent: "Alice",
    subTotal: "600",
    discount: "60",
    taxable: "540",
    tax: "54",
    total: "594",
    status: "Completed",
    createdAt: "2025-09-01",
    updatedAt: "2025-09-03",
    draftedAt: null,
    actionMessage: "Invoice closed",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "8",
    invoiceNumber: "INV-1008",
    customerId: "CUST-008",
    customerName: "Daniel Lee",
    salesAgent: "Bob",
    subTotal: "720",
    discount: "70",
    taxable: "650",
    tax: "65",
    total: "715",
    status: "Pending",
    createdAt: "2025-09-06",
    updatedAt: "2025-09-06",
    draftedAt: null,
    actionMessage: "Waiting approval",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "9",
    invoiceNumber: "INV-1009",
    customerId: "CUST-009",
    customerName: "William Harris",
    salesAgent: "Charlie",
    subTotal: "1500",
    discount: "200",
    taxable: "1300",
    tax: "130",
    total: "1430",
    status: "Completed",
    createdAt: "2025-08-15",
    updatedAt: "2025-08-16",
    draftedAt: null,
    actionMessage: "Invoice paid",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "10",
    invoiceNumber: "INV-1010",
    customerId: "CUST-010",
    customerName: "Isabella Clark",
    salesAgent: "Alice",
    subTotal: "350",
    discount: "25",
    taxable: "325",
    tax: "32.5",
    total: "357.5",
    status: "Draft",
    createdAt: "2025-09-08",
    updatedAt: "2025-09-08",
    draftedAt: "2025-09-08",
    actionMessage: "Draft saved",
    isActive: false,
    isDraft: true,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "11",
    invoiceNumber: "INV-1011",
    customerId: "CUST-011",
    customerName: "James Allen",
    salesAgent: "Bob",
    subTotal: "1100",
    discount: "120",
    taxable: "980",
    tax: "98",
    total: "1078",
    status: "Completed",
    createdAt: "2025-08-10",
    updatedAt: "2025-08-11",
    draftedAt: null,
    actionMessage: "Invoice settled",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "12",
    invoiceNumber: "INV-1012",
    customerId: "CUST-012",
    customerName: "Mia Scott",
    salesAgent: "Charlie",
    subTotal: "250",
    discount: "20",
    taxable: "230",
    tax: "23",
    total: "253",
    status: "Pending",
    createdAt: "2025-09-10",
    updatedAt: "2025-09-10",
    draftedAt: null,
    actionMessage: "Awaiting confirmation",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
];

/*
===============================
# PDF Config
===============================
*/

export const printConfigFieldLabels: ModuleFieldsType = {
  invoiceNumber: "Invoice Number",
  customerId: "Customer ID",
  customerName: "Customer Name",
  salesAgent: "Sales Agent",
  subTotal: "Sub Total",
  discount: "Discount",
  taxable: "Taxable",
  tax: "Tax",
  total: "Total",
};

export type GridDataType = ModuleFieldsType & {
  id: string;
  isDefault: boolean;
  isActive: boolean;
  isDraft: boolean;
  createdAt: Date;
  draftedAt: Date | null;
  updatedAt: Date;
  deletedAt: Date | null;
  isDeleted: boolean;
};

export const GridViewDataList: GridDataType[] = [
  {
    id: "1",
    invoiceNumber: "INV-1001",
    customerId: "CUST-001",
    customerName: "John Doe",
    salesAgent: "Alice",
    subTotal: "500",
    discount: "50",
    taxable: "450",
    tax: "45",
    total: "495",
    isDefault: true,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-01"),
    draftedAt: null,
    updatedAt: new Date("2025-09-02"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "2",
    invoiceNumber: "INV-1002",
    customerId: "CUST-002",
    customerName: "Jane Smith",
    salesAgent: "Bob",
    subTotal: "1200",
    discount: "100",
    taxable: "1100",
    tax: "110",
    total: "1210",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-02"),
    draftedAt: null,
    updatedAt: new Date("2025-09-03"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "3",
    invoiceNumber: "INV-1003",
    customerId: "CUST-003",
    customerName: "Michael Brown",
    salesAgent: "Charlie",
    subTotal: "800",
    discount: "0",
    taxable: "800",
    tax: "80",
    total: "880",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-03"),
    draftedAt: null,
    updatedAt: new Date("2025-09-03"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "4",
    invoiceNumber: "INV-1004",
    customerId: "CUST-004",
    customerName: "Emily Davis",
    salesAgent: "David",
    subTotal: "600",
    discount: "60",
    taxable: "540",
    tax: "54",
    total: "594",
    isDefault: false,
    isActive: false,
    isDraft: true,
    createdAt: new Date("2025-09-04"),
    draftedAt: new Date("2025-09-04"),
    updatedAt: new Date("2025-09-04"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "5",
    invoiceNumber: "INV-1005",
    customerId: "CUST-005",
    customerName: "Chris Wilson",
    salesAgent: "Alice",
    subTotal: "1500",
    discount: "150",
    taxable: "1350",
    tax: "135",
    total: "1485",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-05"),
    draftedAt: null,
    updatedAt: new Date("2025-09-05"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "6",
    invoiceNumber: "INV-1006",
    customerId: "CUST-006",
    customerName: "Sophia Lee",
    salesAgent: "Bob",
    subTotal: "300",
    discount: "30",
    taxable: "270",
    tax: "27",
    total: "297",
    isDefault: false,
    isActive: false,
    isDraft: false,
    createdAt: new Date("2025-09-06"),
    draftedAt: null,
    updatedAt: new Date("2025-09-07"),
    deletedAt: new Date("2025-09-10"),
    isDeleted: true,
  },
  {
    id: "7",
    invoiceNumber: "INV-1007",
    customerId: "CUST-007",
    customerName: "William Taylor",
    salesAgent: "Charlie",
    subTotal: "950",
    discount: "0",
    taxable: "950",
    tax: "95",
    total: "1045",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-07"),
    draftedAt: null,
    updatedAt: new Date("2025-09-08"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "8",
    invoiceNumber: "INV-1008",
    customerId: "CUST-008",
    customerName: "Olivia Martinez",
    salesAgent: "David",
    subTotal: "400",
    discount: "40",
    taxable: "360",
    tax: "36",
    total: "396",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-08"),
    draftedAt: null,
    updatedAt: new Date("2025-09-08"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "9",
    invoiceNumber: "INV-1009",
    customerId: "CUST-009",
    customerName: "James Anderson",
    salesAgent: "Alice",
    subTotal: "1100",
    discount: "100",
    taxable: "1000",
    tax: "100",
    total: "1100",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-09"),
    draftedAt: null,
    updatedAt: new Date("2025-09-10"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "10",
    invoiceNumber: "INV-1010",
    customerId: "CUST-010",
    customerName: "Ava Thomas",
    salesAgent: "Bob",
    subTotal: "700",
    discount: "70",
    taxable: "630",
    tax: "63",
    total: "693",
    isDefault: false,
    isActive: false,
    isDraft: true,
    createdAt: new Date("2025-09-10"),
    draftedAt: new Date("2025-09-10"),
    updatedAt: new Date("2025-09-10"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "11",
    invoiceNumber: "INV-1011",
    customerId: "CUST-011",
    customerName: "Daniel White",
    salesAgent: "Charlie",
    subTotal: "850",
    discount: "85",
    taxable: "765",
    tax: "76.5",
    total: "841.5",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-11"),
    draftedAt: null,
    updatedAt: new Date("2025-09-11"),
    deletedAt: null,
    isDeleted: false,
  },
  {
    id: "12",
    invoiceNumber: "INV-1012",
    customerId: "CUST-012",
    customerName: "Grace Hall",
    salesAgent: "David",
    subTotal: "2000",
    discount: "200",
    taxable: "1800",
    tax: "180",
    total: "1980",
    isDefault: false,
    isActive: true,
    isDraft: false,
    createdAt: new Date("2025-09-12"),
    draftedAt: null,
    updatedAt: new Date("2025-09-12"),
    deletedAt: null,
    isDeleted: false,
  },
];
