/* eslint-disable @typescript-eslint/no-explicit-any */
import FixedColumnDataTable from "@/components/common/country-page-table/FixedColumnDataTable";
import useIsMobile from "@/hooks/useIsMobile";
import { useCountriesPermissions } from "@/hooks/usePermissions";

const mockCountries = [
  {
    id: "1",
    title: "United States",
    flag: "flagcdn.com/us",
    code: "US",
    callingCode: "+1",
    status: "active",
    currency: "USD",
    createdAt: "2023-01-15",
    updatedAt: "2023-11-20",
    draftedAt: "2023-01-10",
    actionMessage: "2 hours ago",
    states: 10,
    cities: 20,
    areas: 40,
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "2",
    title: "Canada",
    flag: "flagcdn.com/ca",
    code: "CA",
    callingCode: "+1",
    status: "active",
    currency: "CAD",
    createdAt: "2023-01-18",
    updatedAt: "2023-10-15",
    draftedAt: "2023-01-12",
    actionMessage: "2 hours ago",
    states: 10,
    cities: 20,
    areas: 40,
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "3",
    title: "United Kingdom",
    flag: "flagcdn.com/gb",
    code: "GB",
    callingCode: "+44",
    status: "active",
    currency: "GBP",
    createdAt: "2023-02-01",
    updatedAt: "2023-11-10",
    draftedAt: "2023-01-25",
    actionMessage: "Yesterday",
    states: 10,
    cities: 20,
    areas: 40,
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "4",
    title: "Germany",
    flag: "flagcdn.com/de",
    code: "DE",
    callingCode: "+49",
    status: "active",
    currency: "EUR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-02-10",
    updatedAt: "2023-11-05",
    draftedAt: "2023-02-05",
    actionMessage: "15 minutes ago",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "5",
    title: "France",
    code: "FR",
    callingCode: "+33",
    status: "active",
    currency: "EUR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-02-15",
    updatedAt: "2023-10-28",
    draftedAt: "2023-02-08",
    actionMessage: "15 Apr 2023",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "6",
    title: "Japan",
    code: "JP",
    callingCode: "+81",
    status: "active",
    currency: "JPY",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-03-01",
    updatedAt: "2023-11-15",
    draftedAt: "2023-02-20",
    actionMessage: "15 Apr 2024",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "7",
    title: "Australia",
    code: "AU",
    callingCode: "+61",
    status: "active",
    currency: "AUD",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-03-10",
    updatedAt: "2023-11-08",
    draftedAt: "2023-03-05",
    actionMessage: "15 Apr 2024",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "8",
    title: "Brazil",
    code: "BR",
    callingCode: "+55",
    status: "active",
    currency: "BRL",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-03-20",
    updatedAt: "2023-10-22",
    draftedAt: "2023-03-15",
    actionMessage: "15 Apr 2024",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "9",
    title: "India",
    code: "IN",
    callingCode: "+91",
    status: "active",
    currency: "INR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-04-01",
    updatedAt: "2023-11-25",
    draftedAt: "2023-03-25",
    actionMessage: "15 Apr 2024",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "10",
    title: "China",
    code: "CN",
    callingCode: "+86",
    status: "active",
    currency: "CNY",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-04-10",
    updatedAt: "2023-11-18",
    draftedAt: "2023-04-05",
    actionMessage: "2 hours ago",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "11",
    title: "Russia",
    code: "RU",
    callingCode: "+7",
    status: "inactive",
    currency: "RUB",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-04-15",
    updatedAt: "2023-09-10",
    draftedAt: "2023-04-10",
    actionMessage: "2 hours ago",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "12",
    title: "South Korea",
    code: "KR",
    callingCode: "+82",
    status: "active",
    currency: "KRW",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-05-01",
    updatedAt: "2023-11-12",
    draftedAt: "2023-04-25",
    actionMessage: "2 hours ago",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "13",
    title: "Mexico",
    code: "MX",
    callingCode: "+52",
    status: "active",
    currency: "MXN",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-05-10",
    updatedAt: "2023-10-30",
    draftedAt: "2023-05-05",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "14",
    title: "Italy",
    code: "IT",
    callingCode: "+39",
    status: "active",
    currency: "EUR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-05-20",
    updatedAt: "2023-11-02",
    draftedAt: "2023-05-15",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "15",
    title: "Spain",
    code: "ES",
    callingCode: "+34",
    status: "active",
    currency: "EUR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-06-01",
    updatedAt: "2023-11-08",
    draftedAt: "2023-05-25",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "16",
    title: "Netherlands",
    code: "NL",
    callingCode: "+31",
    status: "active",
    currency: "EUR",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-06-10",
    updatedAt: "2023-10-25",
    draftedAt: "2023-06-05",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "17",
    title: "Switzerland",
    code: "CH",
    callingCode: "+41",
    status: "draft",
    currency: "CHF",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-06-15",
    updatedAt: "2023-06-20",
    draftedAt: "2023-06-12",
    isActive: false,
    isDraft: true,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "18",
    title: "Sweden",
    code: "SE",
    callingCode: "+46",
    status: "active",
    currency: "SEK",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-07-01",
    updatedAt: "2023-11-15",
    draftedAt: "2023-06-25",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "19",
    title: "Norway",
    code: "NO",
    callingCode: "+47",
    status: "active",
    currency: "NOK",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-07-10",
    updatedAt: "2023-10-18",
    draftedAt: "2023-07-05",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "20",
    title: "Argentina",
    code: "AR",
    callingCode: "+54",
    status: "inactive",
    currency: "ARS",
    states: 10,
    cities: 20,
    areas: 40,
    createdAt: "2023-07-20",
    updatedAt: "2023-09-15",
    draftedAt: "2023-07-15",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },

  {
    id: "21",
    title: "Mexico",
    code: "MX",
    callingCode: "+52",
    status: "active",
    currency: "MXN",
    states: 32,
    cities: 60,
    areas: 150,
    createdAt: "2023-06-15",
    updatedAt: "2023-08-10",
    draftedAt: "2023-06-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "22",
    title: "Spain",
    code: "ES",
    callingCode: "+34",
    status: "inactive",
    currency: "EUR",
    states: 17,
    cities: 45,
    areas: 110,
    createdAt: "2023-07-02",
    updatedAt: "2023-09-15",
    draftedAt: "2023-06-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "23",
    title: "Japan",
    code: "JP",
    callingCode: "+81",
    status: "active",
    currency: "JPY",
    states: 47,
    cities: 90,
    areas: 200,
    createdAt: "2023-04-10",
    updatedAt: "2023-07-25",
    draftedAt: "2023-04-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "24",
    title: "China",
    code: "CN",
    callingCode: "+86",
    status: "inactive",
    currency: "CNY",
    states: 23,
    cities: 100,
    areas: 250,
    createdAt: "2023-05-01",
    updatedAt: "2023-08-12",
    draftedAt: "2023-04-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "25",
    title: "Australia",
    code: "AU",
    callingCode: "+61",
    status: "active",
    currency: "AUD",
    states: 8,
    cities: 25,
    areas: 70,
    createdAt: "2023-03-20",
    updatedAt: "2023-07-05",
    draftedAt: "2023-03-10",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "26",
    title: "New Zealand",
    code: "NZ",
    callingCode: "+64",
    status: "inactive",
    currency: "NZD",
    states: 16,
    cities: 30,
    areas: 80,
    createdAt: "2023-06-05",
    updatedAt: "2023-08-22",
    draftedAt: "2023-05-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "27",
    title: "South Africa",
    code: "ZA",
    callingCode: "+27",
    status: "active",
    currency: "ZAR",
    states: 9,
    cities: 35,
    areas: 100,
    createdAt: "2023-02-11",
    updatedAt: "2023-05-30",
    draftedAt: "2023-02-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "28",
    title: "Russia",
    code: "RU",
    callingCode: "+7",
    status: "inactive",
    currency: "RUB",
    states: 85,
    cities: 120,
    areas: 300,
    createdAt: "2023-03-12",
    updatedAt: "2023-07-18",
    draftedAt: "2023-03-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "29",
    title: "South Korea",
    code: "KR",
    callingCode: "+82",
    status: "active",
    currency: "KRW",
    states: 17,
    cities: 50,
    areas: 130,
    createdAt: "2023-05-18",
    updatedAt: "2023-08-09",
    draftedAt: "2023-05-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "30",
    title: "Thailand",
    code: "TH",
    callingCode: "+66",
    status: "inactive",
    currency: "THB",
    states: 77,
    cities: 40,
    areas: 90,
    createdAt: "2023-07-01",
    updatedAt: "2023-09-10",
    draftedAt: "2023-06-15",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },

  {
    id: "31",
    title: "Italy",
    code: "IT",
    callingCode: "+39",
    status: "active",
    currency: "EUR",
    states: 20,
    cities: 60,
    areas: 140,
    createdAt: "2023-01-11",
    updatedAt: "2023-03-15",
    draftedAt: "2023-01-05",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "32",
    title: "Germany",
    code: "DE",
    callingCode: "+49",
    status: "inactive",
    currency: "EUR",
    states: 16,
    cities: 80,
    areas: 200,
    createdAt: "2023-02-01",
    updatedAt: "2023-04-05",
    draftedAt: "2023-01-25",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "33",
    title: "France",
    code: "FR",
    callingCode: "+33",
    status: "active",
    currency: "EUR",
    states: 18,
    cities: 75,
    areas: 170,
    createdAt: "2023-03-10",
    updatedAt: "2023-06-20",
    draftedAt: "2023-02-28",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "34",
    title: "United Kingdom",
    code: "GB",
    callingCode: "+44",
    status: "inactive",
    currency: "GBP",
    states: 12,
    cities: 55,
    areas: 120,
    createdAt: "2023-04-05",
    updatedAt: "2023-07-15",
    draftedAt: "2023-03-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "35",
    title: "Canada",
    code: "CA",
    callingCode: "+1",
    status: "active",
    currency: "CAD",
    states: 13,
    cities: 65,
    areas: 160,
    createdAt: "2023-05-12",
    updatedAt: "2023-08-20",
    draftedAt: "2023-04-25",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "36",
    title: "Brazil",
    code: "BR",
    callingCode: "+55",
    status: "inactive",
    currency: "BRL",
    states: 26,
    cities: 90,
    areas: 220,
    createdAt: "2023-06-01",
    updatedAt: "2023-08-10",
    draftedAt: "2023-05-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "37",
    title: "Argentina",
    code: "AR",
    callingCode: "+54",
    status: "active",
    currency: "ARS",
    states: 23,
    cities: 70,
    areas: 180,
    createdAt: "2023-07-01",
    updatedAt: "2023-09-05",
    draftedAt: "2023-06-15",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "38",
    title: "Chile",
    code: "CL",
    callingCode: "+56",
    status: "inactive",
    currency: "CLP",
    states: 16,
    cities: 40,
    areas: 100,
    createdAt: "2023-02-10",
    updatedAt: "2023-05-15",
    draftedAt: "2023-02-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "39",
    title: "Colombia",
    code: "CO",
    callingCode: "+57",
    status: "active",
    currency: "COP",
    states: 32,
    cities: 50,
    areas: 120,
    createdAt: "2023-03-18",
    updatedAt: "2023-06-22",
    draftedAt: "2023-03-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "40",
    title: "Peru",
    code: "PE",
    callingCode: "+51",
    status: "inactive",
    currency: "PEN",
    states: 25,
    cities: 45,
    areas: 110,
    createdAt: "2023-04-15",
    updatedAt: "2023-07-18",
    draftedAt: "2023-04-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },

  {
    id: "41",
    title: "Venezuela",
    code: "VE",
    callingCode: "+58",
    status: "active",
    currency: "VES",
    states: 23,
    cities: 48,
    areas: 115,
    createdAt: "2023-01-12",
    updatedAt: "2023-04-20",
    draftedAt: "2023-01-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "42",
    title: "Ecuador",
    code: "EC",
    callingCode: "+593",
    status: "inactive",
    currency: "USD",
    states: 24,
    cities: 40,
    areas: 95,
    createdAt: "2023-02-11",
    updatedAt: "2023-05-25",
    draftedAt: "2023-02-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "43",
    title: "Paraguay",
    code: "PY",
    callingCode: "+595",
    status: "active",
    currency: "PYG",
    states: 17,
    cities: 35,
    areas: 85,
    createdAt: "2023-03-05",
    updatedAt: "2023-06-10",
    draftedAt: "2023-02-20",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "44",
    title: "Uruguay",
    code: "UY",
    callingCode: "+598",
    status: "inactive",
    currency: "UYU",
    states: 19,
    cities: 32,
    areas: 80,
    createdAt: "2023-04-01",
    updatedAt: "2023-07-14",
    draftedAt: "2023-03-22",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "45",
    title: "Bolivia",
    code: "BO",
    callingCode: "+591",
    status: "active",
    currency: "BOB",
    states: 9,
    cities: 28,
    areas: 75,
    createdAt: "2023-05-11",
    updatedAt: "2023-08-16",
    draftedAt: "2023-04-28",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "46",
    title: "Panama",
    code: "PA",
    callingCode: "+507",
    status: "inactive",
    currency: "PAB",
    states: 10,
    cities: 25,
    areas: 60,
    createdAt: "2023-06-08",
    updatedAt: "2023-09-12",
    draftedAt: "2023-05-25",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "47",
    title: "Costa Rica",
    code: "CR",
    callingCode: "+506",
    status: "active",
    currency: "CRC",
    states: 7,
    cities: 20,
    areas: 55,
    createdAt: "2023-02-15",
    updatedAt: "2023-05-22",
    draftedAt: "2023-02-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "48",
    title: "Honduras",
    code: "HN",
    callingCode: "+504",
    status: "inactive",
    currency: "HNL",
    states: 18,
    cities: 30,
    areas: 70,
    createdAt: "2023-03-18",
    updatedAt: "2023-06-25",
    draftedAt: "2023-03-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "49",
    title: "El Salvador",
    code: "SV",
    callingCode: "+503",
    status: "active",
    currency: "USD",
    states: 14,
    cities: 25,
    areas: 65,
    createdAt: "2023-04-14",
    updatedAt: "2023-07-20",
    draftedAt: "2023-04-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "50",
    title: "Guatemala",
    code: "GT",
    callingCode: "+502",
    status: "inactive",
    currency: "GTQ",
    states: 22,
    cities: 35,
    areas: 85,
    createdAt: "2023-05-20",
    updatedAt: "2023-08-24",
    draftedAt: "2023-05-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },

  {
    id: "51",
    title: "Mexico",
    code: "MX",
    callingCode: "+52",
    status: "active",
    currency: "MXN",
    states: 32,
    cities: 100,
    areas: 250,
    createdAt: "2023-06-15",
    updatedAt: "2023-09-10",
    draftedAt: "2023-06-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "52",
    title: "United States",
    code: "US",
    callingCode: "+1",
    status: "inactive",
    currency: "USD",
    states: 50,
    cities: 300,
    areas: 600,
    createdAt: "2023-07-01",
    updatedAt: "2023-10-05",
    draftedAt: "2023-06-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "53",
    title: "Cuba",
    code: "CU",
    callingCode: "+53",
    status: "active",
    currency: "CUP",
    states: 15,
    cities: 35,
    areas: 75,
    createdAt: "2023-01-12",
    updatedAt: "2023-04-15",
    draftedAt: "2023-01-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "54",
    title: "Jamaica",
    code: "JM",
    callingCode: "+1-876",
    status: "inactive",
    currency: "JMD",
    states: 14,
    cities: 20,
    areas: 60,
    createdAt: "2023-02-05",
    updatedAt: "2023-05-20",
    draftedAt: "2023-01-25",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "55",
    title: "Haiti",
    code: "HT",
    callingCode: "+509",
    status: "active",
    currency: "HTG",
    states: 10,
    cities: 22,
    areas: 55,
    createdAt: "2023-03-10",
    updatedAt: "2023-06-15",
    draftedAt: "2023-02-28",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "56",
    title: "Dominican Republic",
    code: "DO",
    callingCode: "+1-809",
    status: "inactive",
    currency: "DOP",
    states: 31,
    cities: 40,
    areas: 100,
    createdAt: "2023-04-01",
    updatedAt: "2023-07-10",
    draftedAt: "2023-03-15",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "57",
    title: "Puerto Rico",
    code: "PR",
    callingCode: "+1-939",
    status: "active",
    currency: "USD",
    states: 8,
    cities: 18,
    areas: 45,
    createdAt: "2023-05-05",
    updatedAt: "2023-08-01",
    draftedAt: "2023-04-20",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "58",
    title: "Trinidad and Tobago",
    code: "TT",
    callingCode: "+1-868",
    status: "inactive",
    currency: "TTD",
    states: 9,
    cities: 16,
    areas: 40,
    createdAt: "2023-06-12",
    updatedAt: "2023-09-08",
    draftedAt: "2023-05-25",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "59",
    title: "Bahamas",
    code: "BS",
    callingCode: "+1-242",
    status: "active",
    currency: "BSD",
    states: 10,
    cities: 12,
    areas: 35,
    createdAt: "2023-07-01",
    updatedAt: "2023-10-01",
    draftedAt: "2023-06-15",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "60",
    title: "Barbados",
    code: "BB",
    callingCode: "+1-246",
    status: "inactive",
    currency: "BBD",
    states: 11,
    cities: 14,
    areas: 38,
    createdAt: "2023-01-20",
    updatedAt: "2023-04-15",
    draftedAt: "2023-01-05",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "61",
    title: "Saint Lucia",
    code: "LC",
    callingCode: "+1-758",
    status: "active",
    currency: "XCD",
    states: 5,
    cities: 10,
    areas: 25,
    createdAt: "2023-02-15",
    updatedAt: "2023-05-12",
    draftedAt: "2023-02-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "62",
    title: "Grenada",
    code: "GD",
    callingCode: "+1-473",
    status: "inactive",
    currency: "XCD",
    states: 6,
    cities: 9,
    areas: 22,
    createdAt: "2023-03-11",
    updatedAt: "2023-06-05",
    draftedAt: "2023-02-25",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "63",
    title: "Saint Vincent and the Grenadines",
    code: "VC",
    callingCode: "+1-784",
    status: "active",
    currency: "XCD",
    states: 5,
    cities: 8,
    areas: 20,
    createdAt: "2023-04-18",
    updatedAt: "2023-07-22",
    draftedAt: "2023-04-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "64",
    title: "Antigua and Barbuda",
    code: "AG",
    callingCode: "+1-268",
    status: "inactive",
    currency: "XCD",
    states: 7,
    cities: 10,
    areas: 24,
    createdAt: "2023-05-12",
    updatedAt: "2023-08-18",
    draftedAt: "2023-05-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "65",
    title: "Dominica",
    code: "DM",
    callingCode: "+1-767",
    status: "active",
    currency: "XCD",
    states: 6,
    cities: 9,
    areas: 21,
    createdAt: "2023-06-01",
    updatedAt: "2023-09-07",
    draftedAt: "2023-05-15",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "66",
    title: "Saint Kitts and Nevis",
    code: "KN",
    callingCode: "+1-869",
    status: "inactive",
    currency: "XCD",
    states: 4,
    cities: 6,
    areas: 15,
    createdAt: "2023-01-25",
    updatedAt: "2023-04-20",
    draftedAt: "2023-01-10",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "67",
    title: "Belize",
    code: "BZ",
    callingCode: "+501",
    status: "active",
    currency: "BZD",
    states: 6,
    cities: 12,
    areas: 28,
    createdAt: "2023-02-18",
    updatedAt: "2023-05-22",
    draftedAt: "2023-02-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "68",
    title: "Guyana",
    code: "GY",
    callingCode: "+592",
    status: "inactive",
    currency: "GYD",
    states: 10,
    cities: 15,
    areas: 35,
    createdAt: "2023-03-22",
    updatedAt: "2023-06-30",
    draftedAt: "2023-03-10",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "69",
    title: "Suriname",
    code: "SR",
    callingCode: "+597",
    status: "active",
    currency: "SRD",
    states: 8,
    cities: 14,
    areas: 30,
    createdAt: "2023-04-10",
    updatedAt: "2023-07-12",
    draftedAt: "2023-03-25",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "70",
    title: "Trinidad",
    code: "TT",
    callingCode: "+1-868",
    status: "inactive",
    currency: "TTD",
    states: 7,
    cities: 13,
    areas: 27,
    createdAt: "2023-05-01",
    updatedAt: "2023-08-02",
    draftedAt: "2023-04-15",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "71",
    title: "Fiji",
    code: "FJ",
    callingCode: "+679",
    status: "active",
    currency: "FJD",
    states: 4,
    cities: 10,
    areas: 22,
    createdAt: "2023-06-15",
    updatedAt: "2023-09-10",
    draftedAt: "2023-06-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "72",
    title: "Samoa",
    code: "WS",
    callingCode: "+685",
    status: "inactive",
    currency: "WST",
    states: 3,
    cities: 7,
    areas: 18,
    createdAt: "2023-07-01",
    updatedAt: "2023-10-01",
    draftedAt: "2023-06-15",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "73",
    title: "Tonga",
    code: "TO",
    callingCode: "+676",
    status: "active",
    currency: "TOP",
    states: 5,
    cities: 9,
    areas: 21,
    createdAt: "2023-01-18",
    updatedAt: "2023-04-14",
    draftedAt: "2023-01-05",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "74",
    title: "Kiribati",
    code: "KI",
    callingCode: "+686",
    status: "inactive",
    currency: "AUD",
    states: 6,
    cities: 8,
    areas: 19,
    createdAt: "2023-02-11",
    updatedAt: "2023-05-22",
    draftedAt: "2023-02-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "75",
    title: "Micronesia",
    code: "FM",
    callingCode: "+691",
    status: "active",
    currency: "USD",
    states: 4,
    cities: 6,
    areas: 15,
    createdAt: "2023-03-05",
    updatedAt: "2023-06-14",
    draftedAt: "2023-02-20",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "76",
    title: "Palau",
    code: "PW",
    callingCode: "+680",
    status: "inactive",
    currency: "USD",
    states: 3,
    cities: 5,
    areas: 12,
    createdAt: "2023-04-09",
    updatedAt: "2023-07-12",
  },
  {
    id: "77",
    title: "Marshall Islands",
    code: "MH",
    callingCode: "+692",
    status: "active",
    currency: "USD",
    states: 2,
    cities: 5,
    areas: 11,
    createdAt: "2023-05-12",
    updatedAt: "2023-08-14",
    draftedAt: "2023-05-01",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "78",
    title: "Tuvalu",
    code: "TV",
    callingCode: "+688",
    status: "inactive",
    currency: "AUD",
    states: 3,
    cities: 4,
    areas: 9,
    createdAt: "2023-06-01",
    updatedAt: "2023-09-05",
    draftedAt: "2023-05-20",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
  {
    id: "79",
    title: "Nauru",
    code: "NR",
    callingCode: "+674",
    status: "active",
    currency: "AUD",
    states: 1,
    cities: 3,
    areas: 7,
    createdAt: "2023-07-01",
    updatedAt: "2023-10-01",
    draftedAt: "2023-06-15",
    isActive: true,
    isDraft: false,
    isDeleted: false,
    isUpdated: true,
  },
  {
    id: "80",
    title: "Vanuatu",
    code: "VU",
    callingCode: "+678",
    status: "inactive",
    currency: "VUV",
    states: 6,
    cities: 8,
    areas: 18,
    createdAt: "2023-01-15",
    updatedAt: "2023-04-12",
    draftedAt: "2023-01-01",
    isActive: false,
    isDraft: false,
    isDeleted: false,
    isUpdated: false,
  },
];

export default function CountriesDataTable2({
  viewMode,
  setViewMode,
  dataTableFilter,
  searchQuery,
  setShowExport,
  showExport,
  setShowFilter,
  showFilter,
  setShowVisibility,
  showVisibility,
  isFilterOpen,
  setIsFilterOpen,
}: {
  viewMode: string;
  setViewMode: (viewMode: string) => void;
  dataTableFilter: any;
  searchQuery: string;
  setShowExport: (showExport: boolean) => void;
  showExport: boolean;
  setShowFilter: (showFilter: boolean) => void;
  showFilter: boolean;
  setShowVisibility: (showVisibility: boolean) => void;
  showVisibility: boolean;
  isFilterOpen: boolean;
  setIsFilterOpen: (isFilterOpen: boolean) => void;
}) {
  const { canCreate } = useCountriesPermissions();
  const isMobile = useIsMobile();

  const componentColumns = [
    {
      accessorKey: "title",
      title: "Name",
      options: [...new Set(mockCountries.map((item) => item.title))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as string;
        return filterValue.some((filterVal: string) =>
          cellValue.toLowerCase().includes(filterVal.toLowerCase())
        );
      },
      sortingFn: (row1: any, row2: any) => {
        return row1.getValue("title").localeCompare(row2.getValue("title"));
      },
      size: isMobile ? 120 : 180,
      minSize: 120,
      meta: {
        exportLabel: "Name",
        readOnly: !canCreate,
      },
    },
    {
      accessorKey: "code",
      title: "Code",
      options: [...new Set(mockCountries.map((item) => item.code))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as string;
        return filterValue.includes(cellValue);
      },
      sortingFn: (row1: any, row2: any) => {
        return row1.getValue("code").localeCompare(row2.getValue("code"));
      },
      size: isMobile ? 80 : 180,
      minSize: 80,
      meta: {
        exportLabel: "code",
        readOnly: !canCreate,
      },
    },
    {
      accessorKey: "callingCode",
      title: "ISD",
      options: [...new Set(mockCountries.map((item) => item.callingCode))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as string;
        return filterValue.includes(cellValue);
      },
      sortingFn: (row1: any, row2: any) => {
        return row1
          .getValue("callingCode")
          .localeCompare(row2.getValue("callingCode"));
      },
      size: isMobile ? 80 : 200,
      minSize: 80,
      meta: {
        exportLabel: "ISD",
        readOnly: true,
      },
    },
    {
      accessorKey: "currency",
      title: "Currency",
      options: [...new Set(mockCountries.map((item) => item.currency))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as string;
        return filterValue.some((filterVal: string) =>
          cellValue.toLowerCase().includes(filterVal.toLowerCase())
        );
      },
      sortingFn: (row1: any, row2: any) => {
        return row1
          .getValue("currency")
          .localeCompare(row2.getValue("currency"));
      },
      size: isMobile ? 80 : 200,
      minSize: 80,
      meta: {
        exportLabel: "Currency",
        readOnly: !canCreate,
      },
    },
    {
      accessorKey: "states",
      title: "States",
      options: [...new Set(mockCountries.map((item) => item.states))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as number;
        if (Array.isArray(filterValue)) {
          return filterValue.some((val: string) =>
            cellValue.toString().includes(val)
          );
        }
        return cellValue.toString().includes(filterValue);
      },
      sortingFn: (row1: any, row2: any) => {
        return row1.getValue("states") - row2.getValue("states");
      },
      size: isMobile ? 80 : 200,
      minSize: 80,
      meta: {
        exportLabel: "States",
        readOnly: true,
      },
    },

    {
      accessorKey: "cities",
      title: "Cities",
      options: [...new Set(mockCountries.map((item) => item.cities))],
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const cellValue = row.getValue(columnId) as number;
        if (Array.isArray(filterValue)) {
          return filterValue.some((val: string) =>
            cellValue.toString().includes(val)
          );
        }
        return cellValue.toString().includes(filterValue);
      },
      sortingFn: (row1: any, row2: any) => {
        return row1.getValue("cities") - row2.getValue("cities");
      },
      size: isMobile ? 80 : 200,
      minSize: 80,
      meta: {
        readOnly: true,
      },
    },

    // {
    //   accessorKey: "areas",
    //   title: "Areas",
    //   options: [...new Set(mockCountries.map((item) => item.areas))],
    //   filterFn: (row: any, columnId: any, filterValue: any) => {
    //     if (!filterValue || filterValue.length === 0) return true;
    //     const cellValue = row.getValue(columnId) as number;
    //     if (Array.isArray(filterValue)) {
    //       return filterValue.some((val: string) =>
    //         cellValue.toString().includes(val)
    //       );
    //     }
    //     return cellValue.toString().includes(filterValue);
    //   },
    //   sortingFn: (row1: any, row2: any) => {
    //     return row1.getValue("areas") - row2.getValue("areas");
    //   },
    //   size: 180,
    //   minSize: 150,
    //   meta: {
    //     readOnly: true,
    //   },
    // },

    {
      accessorKey: "createdAt",
      title: "Created",
      options: [], // Dates are typically not filtered with predefined options
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const dateValue = row.getValue(columnId) as string;
        const date = new Date(dateValue);

        // Check if the date is valid before calling toISOString
        if (isNaN(date.getTime())) {
          return false; // Invalid date, exclude from results
        }

        const cellValue = date.toISOString().split("T")[0];
        return filterValue.includes(cellValue);
      },
      sortingFn: (row1: any, row2: any) => {
        const date1 = new Date(row1.getValue("createdAt"));
        const date2 = new Date(row2.getValue("createdAt"));

        // Handle invalid dates by placing them at the end
        if (isNaN(date1.getTime()) && isNaN(date2.getTime())) return 0;
        if (isNaN(date1.getTime())) return 1;
        if (isNaN(date2.getTime())) return -1;

        return date1.getTime() - date2.getTime();
      },
      size: isMobile ? 150 : 180,
      minSize: 150,
      meta: {
        exportLabel: "createdAt",
        readOnly: true,
      },
    },
    {
      accessorKey: "updatedAt",
      title: "Updated",
      options: [], // Dates are typically not filtered with predefined options
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const dateValue = row.getValue(columnId) as string;
        const date = new Date(dateValue);

        // Check if the date is valid before calling toISOString
        if (isNaN(date.getTime())) {
          return false; // Invalid date, exclude from results
        }

        const cellValue = date.toISOString().split("T")[0];
        return filterValue.includes(cellValue);
      },
      sortingFn: (row1: any, row2: any) => {
        const date1 = new Date(row1.getValue("updatedAt"));
        const date2 = new Date(row2.getValue("updatedAt"));

        // Handle invalid dates by placing them at the end
        if (isNaN(date1.getTime()) && isNaN(date2.getTime())) return 0;
        if (isNaN(date1.getTime())) return 1;
        if (isNaN(date2.getTime())) return -1;

        return date1.getTime() - date2.getTime();
      },
      size: isMobile ? 150 : 180,
      minSize: 150,
      meta: {
        exportLabel: "updatedAt",
        readOnly: true,
      },
    },
    {
      accessorKey: "draftedAt",
      title: "Drafted",
      options: [], // Dates are typically not filtered with predefined options
      filterFn: (row: any, columnId: any, filterValue: any) => {
        if (!filterValue || filterValue.length === 0) return true;
        const dateValue = row.getValue(columnId) as string;
        const date = new Date(dateValue);

        // Check if the date is valid before calling toISOString
        if (isNaN(date.getTime())) {
          return false; // Invalid date, exclude from results
        }

        const cellValue = date.toISOString().split("T")[0];
        return filterValue.includes(cellValue);
      },
      sortingFn: (row1: any, row2: any) => {
        const date1 = new Date(row1.getValue("draftedAt"));
        const date2 = new Date(row2.getValue("draftedAt"));

        // Handle invalid dates by placing them at the end
        if (isNaN(date1.getTime())) return 1;
        if (isNaN(date2.getTime())) return -1;

        return date1.getTime() - date2.getTime();
      },
      size: isMobile ? 150 : 180,
      minSize: 150,
      meta: {
        exportLabel: "draftedAt",
        readOnly: true,
      },
    },
  ];

  const filteredData = mockCountries.filter((country) => {
    if (dataTableFilter.status === "Active") {
      return country.isActive;
    } else if (dataTableFilter.status === "Inactive") {
      return !country.isActive;
    } else if (dataTableFilter.status === "Draft") {
      return country.isDraft;
    } else if (dataTableFilter.status === "Deleted") {
      return country.isDeleted;
    } else if (dataTableFilter.status === "Updated") {
      return country.isUpdated;
    }
    return true;
  });

  return (
    <FixedColumnDataTable
      searchQuery={searchQuery}
      columnData={filteredData}
      viewMode={viewMode}
      setViewMode={setViewMode}
      componentColumns={componentColumns}
      fixedColumns={["title"]} // Pin country name column
      pathName="countries"
      setShowExport={setShowExport}
      showExport={showExport}
      setShowFilter={setShowFilter}
      showFilter={showFilter}
      setShowVisibility={setShowVisibility}
      showVisibility={showVisibility}
      isFilterOpen={isFilterOpen}
      setIsFilterOpen={setIsFilterOpen}
    />
  );
}
